/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PtoB;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
//import PtoB.
/**
 *
 * @author Gonzalo Rivas
 */
public class ChiCuadrado extends javax.swing.JFrame {
    
    NumerosRND frame; //la variable de instancia del JFrame
    int num;// Cantidad de numeros
    int inter;// cantidad de intervalos
    double fesp;// frecuencia esperada
    double vec[];// vector de rnd
    int cont[];//frecuencia observada
    double cont2[];
    double dif[];//diferencia cuadrada para chi  "(Fobs - Fesp)2"
    double difdiv[];//[(Fobs - Fesp)2]/Fesp
    String valInt[];
    double chi[]; // tabla del chiCuadrado
    double chi99[]; // tabla del chiCuadrado
     double nivelConfianza;
    
    DefaultTableModel datos;

    /**
     * Creates new form ChiCuadrado
     */
    public ChiCuadrado(NumerosRND frame) {
       this.frame = frame;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent evt){
                if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del Sistema?","ADVERTENCIA",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {                   
                System.exit(0);
            }               
        }});
        num=frame.getCantNumeros();
        inter=frame.getIntervalo();
         vec = frame.getVecGrafico();
         
      
        datos = new DefaultTableModel(new Object[]{"N°", "Intervalo", "Fobs", "Fesp", "(Fobs - Fesp)2", "[(Fobs - Fesp)2]/Fesp"}, 0);
        calcularValores();
        rellenarTablas();
        jTablaChi.setModel(datos);
        txt_gradolibertad.setText(Integer.toString(inter-1));
        txt_gradolibertad.enable(false);
        txt_chitabulado.enable(false);
        
      
        
        chi=new double[30];
        chi[0]=3.8; // es 1
        chi[1]=6;
        chi[2]=7.8;
        chi[3]=9.5;
        chi[4]=11.1;
        chi[5]=12.6;
        chi[6]=14.1;
        chi[7]=15.5;
        chi[8]=16.9;
        chi[9]=18.3;
        chi[10]=19.7;
        chi[11]=21;
        chi[12]=22.4;
        chi[13]=23.7;
        chi[14]=25;
        chi[15]=26.3;
        chi[16]=27.6;
        chi[17]=28.9;
        chi[18]=30.1;
        chi[19]=31.4;
        chi[20]=32.7;
        chi[21]=33.9;
        chi[22]=35.2;
        chi[23]=36.4;
        chi[24]=37.7;
        chi[25]=38.9;
        chi[26]=40.1;
        chi[27]=41.3;
        chi[28]=42.6;
        chi[29]=43.8; // es 30
        
        chi99 =new double[30];
        chi99[0]=6.6; // es 1
        chi99[1]=9.2;
        chi99[2]=11.3;
        chi99[3]=13.3;
        chi99[4]=15.1;
        chi99[5]=16.8;
        chi99[6]=18.5;
        chi99[7]=20.1;
        chi99[8]=21.7;
        chi99[9]=23.2;
        chi99[10]=24.7;
        chi99[11]=26.2;
        chi99[12]=27.7;
        chi99[13]=29.1;
        chi99[14]=30.6;
        chi99[15]=32.0;
        chi99[16]=33.4;
        chi99[17]=34.8;
        chi99[18]=36.2;
        chi99[19]=37.6;
        chi99[20]=38.9;
        chi99[21]=40.3;
        chi99[22]=41.6;
        chi99[23]=43.0;
        chi99[24]=44.6;
        chi99[25]=45.6;
        chi99[26]=47.0;
        chi99[27]=48.3;
        chi99[28]=49.6;
        chi99[29]=50.9; // es 30
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaChi = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        Rbtn95 = new javax.swing.JRadioButton();
        Rbtn99 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txt_gradolibertad = new javax.swing.JTextField();
        txt_chitabulado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtChi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbtn_calcular = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTablaChi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTablaChi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablaChi);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("Confianza =");

        Rbtn95.setBackground(new java.awt.Color(255, 255, 255));
        Rbtn95.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Rbtn95.setText("0,95");
        Rbtn95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn95ActionPerformed(evt);
            }
        });

        Rbtn99.setBackground(new java.awt.Color(255, 255, 255));
        Rbtn99.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Rbtn99.setText("0,99");
        Rbtn99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn99ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Grados de Libertad =");

        txt_gradolibertad.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_gradolibertad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gradolibertadActionPerformed(evt);
            }
        });

        txt_chitabulado.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_chitabulado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_chitabuladoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("Chi Cuadrado tabulado =");

        jtxtChi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jtxtChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel1.setText("Chi Cuadrado resultante =");

        jbtn_calcular.setBackground(new java.awt.Color(242, 242, 242));
        jbtn_calcular.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jbtn_calcular.setText("Calcular");
        jbtn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_calcularActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setText("Decisión:");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_chitabulado, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jbtn_calcular))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Rbtn95)
                                        .addGap(18, 18, 18)
                                        .addComponent(Rbtn99))
                                    .addComponent(txt_gradolibertad, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtChi, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rbtn95)
                            .addComponent(jLabel3)
                            .addComponent(Rbtn99))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_gradolibertad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_chitabulado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jbtn_calcular)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_gradolibertadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gradolibertadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gradolibertadActionPerformed

    private void jtxtChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChiActionPerformed

    private void txt_chitabuladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_chitabuladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_chitabuladoActionPerformed

    private void jbtn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_calcularActionPerformed
        // TODO add your handling code here:
      
         if(Rbtn95.isSelected()==true){
        nivelConfianza=chi[Integer.parseInt(txt_gradolibertad.getText())-1];
        }if (Rbtn99.isSelected()==true){
            nivelConfianza=chi99[Integer.parseInt(txt_gradolibertad.getText())-1];
        }
        
        
       
        txt_chitabulado.setText(String.valueOf(nivelConfianza));
        txt_chitabulado.setForeground(Color.red);
        if(Double.parseDouble(jtxtChi.getText())< Double.parseDouble(txt_chitabulado.getText()))
        
        jTextArea1.setText("Como Chi cuadrado observado ( " + 
                jtxtChi.getText() +
                " ) es MENOR a Chi cuadrado tabulado\n con el nivel de confianza y los grados de libertad seleccionados \n" +
                "podemos decir que no rechazaremos la Ho (Hipotesis nula o cero)");
        else jTextArea1.setText("Como Chi cuadrado observado ( " + 
                jtxtChi.getText() +
                " ) es MAYOR a Chi cuadrado tabulado\n con el nivel de confianza y los grados de libertad seleccionados \n" +
                "podemos decir que rechazaremos la Ho (Hipotesis nula o cero) y aceptaremos una H1 (Hipotesis alternativa)");
       
    }//GEN-LAST:event_jbtn_calcularActionPerformed

    private void Rbtn99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn99ActionPerformed
       Rbtn95.setSelected(false);
    }//GEN-LAST:event_Rbtn99ActionPerformed

    private void Rbtn95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn95ActionPerformed
        Rbtn99.setSelected(false);
    }//GEN-LAST:event_Rbtn95ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiCuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Rbtn95;
    private javax.swing.JRadioButton Rbtn99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaChi;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbtn_calcular;
    private javax.swing.JTextField jtxtChi;
    private javax.swing.JTextField txt_chitabulado;
    private javax.swing.JTextField txt_gradolibertad;
    // End of variables declaration//GEN-END:variables

public void calcularValores(){
        cont= new int[inter];// cantidad de valores de acuerdo al intervalo
        dif = new double[inter];// diferencia del chi x intervalo
        
        difdiv = new double[inter];
        
        
        double cte = (1.0000/inter); // divido 1 por el intervalo para obtener la cte que va sumando
        fesp = (double) num/inter;
        System.out.println("ver numero"+num);
         System.out.println("ver intervalo"+inter);
        valInt= new String[inter];
        DecimalFormat RedondearADos = new DecimalFormat("0.0000");
        
        double intfinal = 0.0000;
        double intinicial;
        for (int i = 0; i < inter; i++) {
            intinicial = intfinal;//inicia el limite izq de cada linea
           
            intfinal = (intinicial + cte);//inicial el limite derecho de cada linea
            valInt[i] = RedondearADos.format(intinicial)+" - "+RedondearADos.format(intfinal);

            for (int j = 0; j < vec.length; j++) {//recorre los valores del rnd
                if (vec[j] >= intinicial && vec[j] < intfinal) {//ubica de acuerdo al intervalo               
                    cont[i]++;//cuenta
                }
            }

        }
        for (int i = 0; i < cont.length; i++) {// cacula el cuadrado
            dif[i] = Math.pow((cont[i] - fesp),2);
            difdiv[i]= (dif[i]/fesp);
        }
     
        double acu = 0;
        for (int i = 0; i < dif.length; i++) {
            acu += dif[i];
        }
        System.out.println(acu);
        double chi = acu / fesp;
        jtxtChi.setText(String.valueOf(chi));
        jtxtChi.enable(false);
        
    }

    public void rellenarTablas(){
        for(int i=0;i<inter;i++){
            Object [] fila = new Object[6];
            fila[0]=i;
            fila[1]=valInt[i];
            fila[2]=cont[i];
            fila[3]=fesp;
            fila[4]=dif[i];
            fila[5]=difdiv[i];
            
            datos.addRow(fila);
        }
    }



}
