/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package PtoB;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;
import org.jfree.ui.RefineryUtilities;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import java.util.Random;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author a4
 */
public class NumerosRND extends javax.swing.JFrame {
    
     private int intervalo;
    private int nivelConfianza;
    private int cantNumeros;
    private String vec[];
    private double vecGrafico[];
    DefaultTableModel datos;

    public int getIntervalo() {
        return intervalo;
    }

    public void setIntervalo(int intervalo) {
        this.intervalo = intervalo;
    }

    public int getCantNumeros() {
        return cantNumeros;
    }

    public void setCantNumeros(int cantNumeros) {
        this.cantNumeros = cantNumeros;
    }

    public String[] getVec() {
        return vec;
    }

    public void setVec(String[] vec) {
        this.vec = vec;
    }

    public double[] getVecGrafico() {
        return vecGrafico;
    }

    public void setVecGrafico(double[] vecGrafico) {
        this.vecGrafico = vecGrafico;
    }

    /**
     * Creates new form NumerosRND
     */
    public NumerosRND() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Generacion Numeros Aleatorios");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Rbtn10 = new javax.swing.JRadioButton();
        RBtn5 = new javax.swing.JRadioButton();
        RBtn20 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txt_cantValores = new javax.swing.JTextField();
        btn_generar = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btn_Grafico = new javax.swing.JToggleButton();
        btn_chi = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Test de Chi Cuadrado _ Math.random()");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel1.setText("Intervalos =");
        jLabel1.setToolTipText("Número de intervalos");

        Rbtn10.setBackground(new java.awt.Color(255, 255, 255));
        Rbtn10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Rbtn10.setText("10");
        Rbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn10ActionPerformed(evt);
            }
        });

        RBtn5.setBackground(new java.awt.Color(255, 255, 255));
        RBtn5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        RBtn5.setText("5");
        RBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtn5ActionPerformed(evt);
            }
        });

        RBtn20.setBackground(new java.awt.Color(255, 255, 255));
        RBtn20.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        RBtn20.setText("20");
        RBtn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtn20ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("Cantidad Valores =");
        jLabel3.setToolTipText("Cantidad de valores a generar");

        txt_cantValores.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        btn_generar.setBackground(new java.awt.Color(242, 242, 242));
        btn_generar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btn_generar.setText("Generar");
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero", "xi+1"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btn_Grafico.setBackground(new java.awt.Color(242, 242, 242));
        btn_Grafico.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btn_Grafico.setText("Grafico");
        btn_Grafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GraficoActionPerformed(evt);
            }
        });

        btn_chi.setBackground(new java.awt.Color(242, 242, 242));
        btn_chi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btn_chi.setText("Chi cuadrado");
        btn_chi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(59, 59, 59)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(RBtn5)
                                .addGap(10, 10, 10)
                                .addComponent(Rbtn10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RBtn20))
                            .addComponent(txt_cantValores, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(btn_chi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(btn_Grafico, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 30, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(RBtn5)
                    .addComponent(RBtn20)
                    .addComponent(Rbtn10))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_cantValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_chi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Grafico, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn10ActionPerformed
        RBtn5.setSelected(false);
        RBtn20.setSelected(false);
    }//GEN-LAST:event_Rbtn10ActionPerformed

    private void RBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtn5ActionPerformed
        Rbtn10.setSelected(false);
        RBtn20.setSelected(false);
    }//GEN-LAST:event_RBtn5ActionPerformed

    private void RBtn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtn20ActionPerformed
        Rbtn10.setSelected(false);
        RBtn5.setSelected(false);
    }//GEN-LAST:event_RBtn20ActionPerformed

    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed

        cantNumeros = Integer.parseInt(txt_cantValores.getText());
        GeneradorRND r= new GeneradorRND(cantNumeros);

        vec = new String[cantNumeros];
        vecGrafico= new double[cantNumeros];

        DecimalFormat truncado = new DecimalFormat("0.0000");

        datos = new DefaultTableModel(new Object[]{"numero", "Xi+1"}, 0);
        jTable2.setModel(datos);

        for (int i = 0; i < cantNumeros; i++) {

            double g =  r.getRandom();
            vecGrafico[i] = g;
            vec[i] = truncado.format(g) + "\n";

            // System.out.println("ver vec: "+vec[i]);
            //System.out.println("ver vecGrafico: "+ vecGrafico[i]);
            // Coinciden

        }

        if(Rbtn10.isSelected()==true){
            this.intervalo=10;
        }if (RBtn5.isSelected()==true){
            this.intervalo=5;
        }if (RBtn20.isSelected()==true){
            this.intervalo=20;
        }
        for (int i = 0; i < cantNumeros; i++) {
            Object[] fila = new Object[2];
            fila[0] = (i + 1);
            fila[1] = vec[i];

            datos.addRow(fila);
        }

    }//GEN-LAST:event_btn_generarActionPerformed

    private void btn_GraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GraficoActionPerformed

        try{

            Histograma histo = new Histograma("Histograma", vecGrafico, intervalo);
            histo.pack();
            RefineryUtilities.centerFrameOnScreen(histo);
            histo.setVisible(true);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "No se ingresaron los datos", "Error Histograma", WIDTH);
        }
        catch(ClassCastException e){
            JOptionPane.showMessageDialog(rootPane, "No se ingresaron los datos", "Error Histograma", WIDTH);
        }

    }//GEN-LAST:event_btn_GraficoActionPerformed

    private void btn_chiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chiActionPerformed
        ChiCuadrado m = new ChiCuadrado(this);
        m.setVisible(true);
    }//GEN-LAST:event_btn_chiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumerosRND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumerosRND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumerosRND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumerosRND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumerosRND().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBtn20;
    private javax.swing.JRadioButton RBtn5;
    private javax.swing.JRadioButton Rbtn10;
    private javax.swing.JToggleButton btn_Grafico;
    private javax.swing.JToggleButton btn_chi;
    private javax.swing.JToggleButton btn_generar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txt_cantValores;
    // End of variables declaration//GEN-END:variables
}
