/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PtoB;

/**
 *
 * @author a3
 */
public class TestChiCuadradoRND extends javax.swing.JFrame {

    private int intervalo;
    private int nivelConfianza;
    private int cantNumeros;
    /**
     * Creates new form TestDeChiCuadrado
     */
    public TestChiCuadradoRND() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Test de Chi Cuadrado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Rbtn10 = new javax.swing.JRadioButton();
        RBtn50 = new javax.swing.JRadioButton();
        RBtn100 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txt_cantValores = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        RBtn95 = new javax.swing.JRadioButton();
        RBtn99 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_fe = new javax.swing.JTextField();
        btn_generar = new javax.swing.JToggleButton();
        txt_fo = new javax.swing.JTextField();

        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Test de Chi Cuadrado _ Math.random()");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("K =");
        jLabel1.setToolTipText("Número de intervalos");

        Rbtn10.setBackground(new java.awt.Color(255, 255, 255));
        Rbtn10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Rbtn10.setForeground(new java.awt.Color(0, 0, 0));
        Rbtn10.setText("10");
        Rbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn10ActionPerformed(evt);
            }
        });

        RBtn50.setBackground(new java.awt.Color(255, 255, 255));
        RBtn50.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        RBtn50.setForeground(new java.awt.Color(0, 0, 0));
        RBtn50.setText("50");
        RBtn50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtn50ActionPerformed(evt);
            }
        });

        RBtn100.setBackground(new java.awt.Color(255, 255, 255));
        RBtn100.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        RBtn100.setForeground(new java.awt.Color(0, 0, 0));
        RBtn100.setText("100");
        RBtn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtn100ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("M =");
        jLabel3.setToolTipText("Cantidad de valores a generar");

        txt_cantValores.setBackground(new java.awt.Color(255, 255, 255));
        txt_cantValores.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_cantValores.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nivel de confianza ");

        RBtn95.setBackground(new java.awt.Color(255, 255, 255));
        RBtn95.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        RBtn95.setForeground(new java.awt.Color(0, 0, 0));
        RBtn95.setText("95%");
        RBtn95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtn95ActionPerformed(evt);
            }
        });

        RBtn99.setBackground(new java.awt.Color(255, 255, 255));
        RBtn99.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        RBtn99.setForeground(new java.awt.Color(0, 0, 0));
        RBtn99.setText("99%");
        RBtn99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtn99ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Frec. Esperada");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Frec. Observada");

        txt_fe.setBackground(new java.awt.Color(255, 255, 255));
        txt_fe.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_fe.setForeground(new java.awt.Color(0, 0, 0));
        txt_fe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_feActionPerformed(evt);
            }
        });

        btn_generar.setBackground(new java.awt.Color(242, 242, 242));
        btn_generar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btn_generar.setText("Generar");
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });

        txt_fo.setBackground(new java.awt.Color(255, 255, 255));
        txt_fo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_fo.setForeground(new java.awt.Color(0, 0, 0));
        txt_fo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_foActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RBtn95)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RBtn99)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_cantValores, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_fe, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Rbtn10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RBtn50)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RBtn100))
                                    .addComponent(txt_fo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Rbtn10)
                    .addComponent(RBtn50)
                    .addComponent(RBtn100))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_cantValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RBtn95)
                    .addComponent(RBtn99)
                    .addComponent(btn_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_fe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_fo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RBtn95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtn95ActionPerformed
        RBtn99.setSelected(false);
    }//GEN-LAST:event_RBtn95ActionPerformed

    private void Rbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn10ActionPerformed
        RBtn50.setSelected(false);
        RBtn100.setSelected(false);
    }//GEN-LAST:event_Rbtn10ActionPerformed

    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed
        int cantNros = Integer.parseInt(txt_cantValores.getText());
        GeneradorRND r= new GeneradorRND(cantNros);
        for (int i = 0; i < cantNros; i++) {
             System.out.println(r.getRandom());
        }
       
        if(Rbtn10.isSelected()==true){
            this.intervalo=10;
        }if (RBtn50.isSelected()==true){
            this.intervalo=50;
        }if (RBtn100.isSelected()==true){
            this.intervalo=100;
        }
        if (RBtn95.isSelected()==true){
            this.nivelConfianza=95;
        }else
            this.nivelConfianza=99;
     
        System.exit(0);
    }//GEN-LAST:event_btn_generarActionPerformed

    private void RBtn50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtn50ActionPerformed
        Rbtn10.setSelected(false);
        RBtn100.setSelected(false);
    }//GEN-LAST:event_RBtn50ActionPerformed

    private void RBtn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtn100ActionPerformed
        Rbtn10.setSelected(false);
        RBtn50.setSelected(false);
    }//GEN-LAST:event_RBtn100ActionPerformed

    private void RBtn99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtn99ActionPerformed
       RBtn95.setSelected(false);
    }//GEN-LAST:event_RBtn99ActionPerformed

    private void txt_feActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_feActionPerformed
      
    }//GEN-LAST:event_txt_feActionPerformed

    private void txt_foActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_foActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_foActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestChiCuadradoRND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestChiCuadradoRND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestChiCuadradoRND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestChiCuadradoRND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestChiCuadradoRND().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBtn100;
    private javax.swing.JRadioButton RBtn50;
    private javax.swing.JRadioButton RBtn95;
    private javax.swing.JRadioButton RBtn99;
    private javax.swing.JRadioButton Rbtn10;
    private javax.swing.JToggleButton btn_generar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_cantValores;
    private javax.swing.JTextField txt_fe;
    private javax.swing.JTextField txt_fo;
    // End of variables declaration//GEN-END:variables
}
